# Generated by Django 4.0.4 on 2022-11-16 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='CÓDIGO')),
                ('name', models.CharField(max_length=40, verbose_name='CARRERA')),
                ('description', models.CharField(max_length=200, verbose_name='RESUMEN')),
                ('creditos', models.PositiveSmallIntegerField(verbose_name='CRÉDITOS')),
            ],
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='CÓDIGO')),
                ('name', models.CharField(max_length=20, verbose_name='NOMBRE')),
                ('lastname', models.CharField(max_length=20, verbose_name='APELLIDO')),
                ('document', models.PositiveIntegerField(unique=True, verbose_name='CÉDULA')),
                ('mail', models.EmailField(max_length=254, verbose_name='CORREO')),
            ],
        ),
        migrations.CreateModel(
            name='Facultad',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='CÓDIGO')),
                ('name', models.CharField(max_length=40, verbose_name='FACULTAD')),
                ('description', models.CharField(max_length=200, verbose_name='RESUMEN')),
                ('decano', models.CharField(max_length=40, verbose_name='DECANO')),
                ('secretary', models.CharField(max_length=40, verbose_name='SECRETARIA')),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='CÓDIGO')),
                ('name', models.CharField(max_length=30, verbose_name='CURSO')),
                ('description', models.CharField(blank=True, max_length=30, null=True, verbose_name='CURSO')),
                ('begin', models.DateField(verbose_name='Fecha inicio')),
                ('end', models.DateField(verbose_name='Fecha terminación')),
                ('creditos', models.PositiveSmallIntegerField(verbose_name='CRÉDITOS')),
                ('horario', models.CharField(choices=[('D', 'DIURNO'), ('N', 'NOCTURNO'), ('FDS', 'FIN DE SEMANA')], max_length=3, verbose_name='JORNADA')),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.carrera')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academico.docente')),
            ],
        ),
        migrations.AddField(
            model_name='carrera',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.facultad', verbose_name='FACULTAD'),
        ),
    ]
